diesis_prec = {
    "Durg reaction":"\n Take following measures : \n Stop taking Drug",
    "Malaria":" \n Consult nearest hospital \n avoid oily food \n avoid non veg food \n keep mosquitos out",
    "Allergy":" \n apply calamine \n cover area with bandage \n  use ice to compress itching ",
    "Hypothyroidism":"\n reduce stress \n exercise \n eat healthy \n get proper sleep",
    "Psoriasis":"\n Psoriasis \n wash hands with warm soapy water \n stop bleeding using pressure \n consult doctor \n salt baths",
    "Gerd":"\n avoid fatty spicy food \n avoid lying down after eating \n maintain healthy weight \n exercise",
    "Chronic cholestasis":"\n cold baths \n anti itch medicine \n consult doctor\n eat healthy",
    "hepatitis":"\n Consult nearest hospital\n wash hands through\n avoid fatty spicy food\n medication",
    "Osteoarthristis":"\n acetaminophen\n consult nearest hospital\n follow up\n salt baths",
    "(vertigo) paroymsal  positional vertigo":"\n lie down\n avoid sudden change in body \n avoid abrupt head movment\n relax",
    "Hypoglycemia":"\n lie down on side \n check in pulse \n drink sugary drinks \n consult doctor",
    "Acne":"\n bath twice \n avoid fatty spicy food \n drink plenty of water \n avoid too many products",
    "Diabetes":"\n have balanced diet\n exercise\n consult doctor \n follow up",
    "Impetigo":"\n soak affected area in warm water\n use antibiotics\n remove scabs with wet compressed cloth\n consult doctor",
    "Hypertension":"\n meditation\n salt baths\n reduce stress\n get proper sleep",
    "Peptic ulcer diseae":"\n avoid fatty spicy food\n consume probiotic food\n eliminate milk\nlimit alcohol",
    "Dimorphic hemmorhoids(piles)":"\n avoid fatty spicy food\n consume witch hazel\n warm bath with epsom salt\n consume alovera juice",
    "Common cold":"\n drink vitamin c rich drinks\n take vapour\n avoid cold food\n keep fever in check",
    "Chicken pox":"\n use neem in bathing \n consume neem leaves\n take vaccine\n avoid public places",
    "Cervical spondylosis":"\n use heating pad or cold pack\n exercise\n take otc pain reliver\n consult doctor",
    "Hyperthyroidism":"\n eat healthy\n massage\n use lemon balm\n take radioactive iodine treatment",
    "Urinary tract infection":"\n drink plenty of water\n increase vitamin c intake\n drink cranberry juice\n take probiotics",
    "Varicose veins":"\n lie down flat and raise the leg high\n use oinments\n use vein compression\n dont stand still for long",
    "Aids":"\n avoid open cuts\n wear ppe if possible\n  consult doctor\n follow up",
    "Paralysis (brain hemorrhage)":"\n massage\n eat healthy\n exercise\n consult doctor",
    "Typhoid":"\n eat high calorie vegitables\n antiboitic therapy\n consult doctor\n medication",
    "Hepatitis b":"\n consult nearest hospital\n vaccination\n eat healthy\n medication",
    "Hepatitis a":"\n consult nearest hospital\n vaccination\n eat healthy\n medication",
    "Fungal infection":"\n bath twice\n use detol or neem in bathing water\n keep infected area dry\n use clean cloths",
    "Hepatitis c":"\n Consult nearest hospital\n vaccination\n eat healthy\n medication",
    "Migraine":"\n meditation\n reduce stress\n use poloroid glasses in sun\n consult doctor",
    "Bronchial asthma":"\n switch to loose cloothing\n take deep breaths\n get away from trigger\n seek help",
    "Alcoholic hepatitis":"\n stop alcohol consumption\n consult doctor\n medication\n follow up",
    "Jaundice":"\n drink plenty of water\n consume milk thistle\n eat fruits and high fiberous food\n medication",
    "Hepatitis e":"\n stop alcohol consumption\n rest\n consult doctor\n medication",
    "Dengue":"\n drink papaya leaf juice\n avoid fatty spicy food\n keep mosquitos away\n keep hydrated",
    "Hepatitis d":"\n consult doctor\n medication\n eat healthy\n follow up",
    "Heart attack":"\n call ambulance\n chew or swallow asprin\n keep calm\n ",
    "Pneumonia":"\n consult doctor\n medication\n rest\n follow up",
    "Arthritis":"\n exercise\n use hot and cold therapy\n try acupuncture\n massage",
    "Gastroenteritis":"\n stop eating solid food for while\n try taking small sips of water\n rest\n ease back into eating",
    "Tuberculosis":"\n cover mouth\n consult doctor\n medication\n rest",
}
